= About the macros branch =

This branch is intended to follow the evolution of
https://github.com/OlivierNicole/ocaml/tree/macros_unstable[macros_unstable].
`macros_unstable` is merged into this branch on a regular basis, once a set of
changes has been applied and the tests run.

== Overview

This is an experimental implementation of OCaml macros, originally designed by
Leo White and Jeremy Yallop:

http://www.lpw25.net/ocaml2015-abs1.pdf

You can find a summary of the current progress here:

https://oliviernicole.github.io/about_macros.html

This branch is based on version 4.04 of OCaml.

== Installation

Installation instruction are the same as for the standard OCaml distribution.
You can find a few examples of what is possible in the links above. You can also
take a look at the `testsuite/tests/macros/` directory.

== Contributing

You are very welcome to try out macros. Please do report any bugs or
inconvenience by opening an issue on this repo.

=== Pull requests

Found a bug and know how to fix it? We certainly appreciate pull requests.
If you plan on making big changes, please file an issue first to discuss why
theses changes are needed.

== List of Contributors

The implementation of macros is an https://github.com/ocamllabs[OCaml Labs]
research project.

Main collaborators:

* Olivier Nicole, main developer 
* Leo White, quoting library, original design and supervision
* Jeremy Yallop, original design and supervision
* Oleg Kiselyov, developer of BER MetaOCaml, from which macros are inspired
* Gemma Gordon, project manager
