= About the macros branch =

https://github.com/OlivierNicole/ocaml/tree/macros_unstable[macros_unstable] is
merged into https://github.com/OlivierNicole/ocaml/tree/macros[macros] on a
regular basis, once a set of changes has been applied and the tests run.

== Overview

This is an experimental implementation of OCaml macros, originally designed by
Leo White and Jeremy Yallop:

http://www.lpw25.net/ocaml2015-abs1.pdf

You can find a summary of the current progress here:

https://oliviernicole.github.io/about_macros.html

This branch is based on version 4.04 of OCaml.

== Installation

Installation instruction are the same as for the standard OCaml distribution.
You can find a few examples of what is possible in the links above. You can also
take a look at the `testsuite/tests/macros/` directory.

=== Installing OPAM packages

You may want to set up a switch with this version of the compiler in order to
install packages. However, quite a lot of packages currently fail to compile for
one of the following reasons:

* a backward-incompatibility in the syntax. The most prevalent incompatibility
is expressions like `"str"^M.foo`, without spaces around `^`, which is parsed as
a string, followed by a lifted path. These incompatibilities are generally very
quick to fix, so if you encounter one, don't hesitate to file a pull request!
Other possible syntax errors:
** a use of the reserved words `static` or `macro` as an identifier;
** a use of `$` as a regular operator.
* a wrong depency tree. A compilation unit may now have both static and run-time
dependencies, and `ocamldep` has not yet been updated to take into account the
static ones. A fix is on its way.

The following packages are known to be broken with macros:

* ocamlbuild (syntax error, pull request pending). As a temporary workaround,
you can pin ocamlbuild to this https://github.com/OlivierNicole/ocamlbuild[fixed
repo].
* camlp4: syntax errors, differences with the compiler AST and wrong dependency
tree. I'm working on a fix.

== Contributing

You are very welcome to try out macros. Please do report any bugs or
inconvenience by opening an issue on this repo.

=== Pull requests

Found a bug and know how to fix it? We certainly appreciate pull requests.
If you plan on making big changes, please file an issue first to discuss why
theses changes are needed.

== List of Contributors

The implementation of macros is an https://github.com/ocamllabs[OCaml Labs]
research project.

Main collaborators:

* Olivier Nicole, main developer 
* Leo White, quoting library, original design and supervision
* Jeremy Yallop, original design and supervision
* Oleg Kiselyov, developer of BER MetaOCaml, from which macros are inspired
* Gemma Gordon, project manager
